### ISSUE TITLE
Cannot create class it.achdjian.plugin.esp32.setting.ESP32Setting

### ISSUE THREAD

**Issue by maxd** [paoloach/ESP32#10]
I have received the following error on ESP32 configuration page in settings:

```
com.intellij.diagnostic.PluginException: Cannot create class it.achdjian.plugin.esp32.setting.ESP32Setting [Plugin: it.achdjian.plugin.ESP322]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:656)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:685)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:422)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:329)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:45)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:119)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:94)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.prepare(ConfigurableCardPanel.java:44)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.prepare(ConfigurableCardPanel.java:35)
	at com.intellij.ui.CardLayoutPanel.lambda$selectLater$1(CardLayoutPanel.java:122)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:615)
	... 20 more
Caused by: java.lang.UnsatisfiedLinkError: Native Library /Users/xxx/.jssc/mac_os_x/libjSSC-2.8_x86_64.jnilib already loaded in another classloader
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2468)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at jssc.SerialNativeInterface.<clinit>(SerialNativeInterface.java:172)
	at it.achdjian.plugin.esp32.serial.ESP32SerialPortList.<init>(ESP32SerialPortList.kt:45)
	at it.achdjian.plugin.esp32.ui.SerialPortListComboBox.<init>(SerialPortListComboBox.kt:13)
	at it.achdjian.plugin.esp32.setting.ESP32Setting.<init>(ESP32Setting.kt:99)
	... 25 more
```

Looks like `Arduino Support` plug-in is using `jssc` library already. When I have disabled it the problem is disappear.

```
CLion 2020.2.3
Build #CL-202.7319.72, built on September 17, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.intellij.kotlinNative.platformDeps, com.jetbrains.plugins.ini4idea, it.achdjian.plugin.ESP322, org.jetbrains.kotlin.native.clion
```

**Comment by paoloach** [comment]
Hi Maxd,

thank you for the notification.
I will try to resolve it.

Until now, please, use your workaround.

Regards,
Paolo

Il giorno lun 21 set 2020 alle ore 10:51 maxd <notifications@github.com> ha
scritto:
