### ISSUE TITLE
Exception when trying to debug using JTAG

### ISSUE THREAD

**Issue by bamkrs** [paoloach/ESP32#13]
I'm using a ESP-WROVER-KIT and am trying to debug a simple blinky-app. However, when I press the debug-button the following exception is thrown:

```
java.lang.NoSuchMethodError: 'void com.jetbrains.cidr.execution.debugger.remote.CidrRemoteDebugParameters.<init>(java.lang.String, java.lang.String, java.lang.String, java.util.List, java.util.List, int, kotlin.jvm.internal.DefaultConstructorMarker)'
	at it.achdjian.plugin.esp32.configurations.debuger.ESP32DebugLauncher.<init>(ESP32DebugLauncher.kt:112)
	at it.achdjian.plugin.esp32.configurations.debuger.ESP32DebugConfiguration.getState(ESP32DebugConfiguration.kt:49)
	at it.achdjian.plugin.esp32.configurations.debuger.ESP32DebugConfiguration.getState(ESP32DebugConfiguration.kt:23)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:216)
	at com.intellij.execution.ExecutionManager.startRunProfile(ExecutionManager.kt:59)
	at com.jetbrains.cidr.execution.CidrRunner.execute(CidrRunner.java:33)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration(ExecutionManagerImpl.kt:662)
	at com.intellij.execution.impl.ExecutionManagerImpl.executeConfiguration$default(ExecutionManagerImpl.kt:621)
	at com.intellij.execution.impl.ExecutionManagerImpl$restartRunProfile$1.run(ExecutionManagerImpl.kt:520)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:376)
	at com.intellij.util.Alarm$Request.run(Alarm.java:362)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I'm using CLion 2020.3.1 with the newest IDF version to this date.

**Comment by dFohlen** [comment]
Same with ESP32-WROOM dev board on macOS BigSur 11.1 (20C69) and CLion 2020.3.2 😉
